name: Notify PharmaGO

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send event to PharmaGO
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/CareOP/PharmaGO/dispatches \
          -d '{
            "event_type": "repo_push",
            "client_payload": {
              "repo": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "author": "${{ github.actor }}"
            }
          }'
